name: demo_first_week
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  formz: ^0.4.1
  equatable: ^2.0.3
  http: ^0.13.4

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  
  fonts:
    - family: FSBold
      fonts:
        - asset: assets/fonts/FiraSans-Bold.ttf
          weight: 700
    - family: FSLight
      fonts:    
        - asset: assets/fonts/FiraSans-Light.ttf
          weight: 300
    - family: FSRegular
      fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf
          weight: 400
    - family: FSSemi
      fonts:
        - asset: assets/fonts/FiraSans-SemiBold.ttf
          weight: 600

